name: Planifolia Core
id: core

stages:
- id: build
  base: ghcr.io/archlinux/archlinux:base
  singlelayer: false
  labels:
    maintainer: nisel11

  modules:
  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-abroot.yml
      - modules/00-vanilla-apx.yml
      - modules/01-manpages.yml
      - modules/02-kernel.yml
      - modules/03-fswarn.yml
      - modules/04-firmware.yml
      - modules/05-input-and-locale.yml
      - modules/06-ssh.yml
      - modules/07-utils.yml
      - modules/08-essentials.yml
      - modules/09-fs.yml
      - modules/10-sound.yml
      - modules/11-compression.yml
      - modules/12-xdg.yml
      - modules/13-network.yml
      - modules/14-packages.yml
      - modules/15-boot.yml
      - modules/16-services.yml
      - modules/17-init-executable.yml

  - name: fsguard
    type: fsguard
    FsGuardLocation: "/usr/libexec/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
