name: Planifolia Core
id: core

stages:
- id: build
  base: ghcr.io/archlinux/archlinux:base
  singlelayer: false
  labels:
    maintainer: nisel11

  modules:
  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-abroot.yml
      - modules/00-vanilla-apx.yml
      - modules/01-packages.yml
      - modules/02-fswarn.yml
      - modules/03-boot.yml
      - modules/04-services.yml
      - modules/05-init-executable.yml

  - name: zram-config
    type: shell
    commands:
      - echo -e "[zram0]\nzram-size = min(ram / 2)\ncompression-algorithm = lz4\n" >> /etc/systemd/zram-generator.conf

  - name: polkit-remember-auth
    type: shell
    commands:
    - sed -ie 's/auth_admin/auth_admin_keep/' /usr/share/polkit-1/actions/org.freedesktop.policykit.policy

  - name: fsguard
    type: fsguard
    FsGuardLocation: "/usr/libexec/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr"]

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
